sonar.verbose=true
sonar.projectKey=vprofile 
sonar.projectName=vprofile 
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes 
sonar.junit.reportsPath=target/surefire-reports 
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml 
